apiVersion: v1
kind: Pod
metadata:
  name: superdeploy-app
  namespace: superdeploy-namespace
  labels:
    app: superdeploy-app
spec:
  containers:
    - name: superdeploy-app
      image: superdeploy
      ports:
        containerPort: 80
