apiVersion: v1
kind: Secret
metadata:
  name: superdeploy-secrets
  namespace: superdeploy-namespace
type: Opaque
stringData:
  POSTGRES_CONN_STRING: postgres://superdeploy:superdeploy@postgres:5432/superdeploy
  JWT_SECRET: change-me-please-this-is-not-a-real-secret