name = "Postgres"
type = "database"
description = "postgres database"

[image]
name = "postgres"
default_tag = "18"

[[volumes]]
type = "mount"
name = "data" # The final name will be <project_slug>-<service_slug>-<name> (name will be this name)
container_dir = "/var/lib/postgres/data"

[user_select.db_name]
name = "Postgres database name"
description = "foo bar buzz"

[user_select.db_user]
name = "Postgres user"
description = "foo bar buzz"
